"""add phone number to users

Revision ID: 28d2b237b6f5
Revises: 76036cfb45f1
Create Date: 2022-01-12 23:06:25.266695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d2b237b6f5'
down_revision = '76036cfb45f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    # ### end Alembic commands ###
